gzip_assets: on

javascripts:
  app:
    - public/javascripts/bower_components/modernizr/modernizr.js
    - public/javascripts/tire.js
    - public/javascripts/hamburguer.js
  modernizr:
    - public/javascripts/modernizr.js
    
stylesheets:
  main:
    - public/stylesheets/style.css
  blog:
    - public/stylesheets/blog.css
  ie8:
    - public/stylesheets/ie8.css